### ISSUE TITLE
syntax error, unexpected T_STRING ... on line 11

### ISSUE THREAD

**Issue by loredev10** [DanielFloeter/same-category-posts#9]
I'm using WordPress 4.2.15 and while in the 'Install now' menu the plugin is marked as compatible with my version of WP, after download and install I get a fatal error:

Parse error: syntax error, unexpected T_STRING in /home/imageua/image.ua/www/wp-content/plugins/same-category-posts/same-category-posts.php on line 11

The line is: namespace sameCategoryPosts;

**Comment by DanielFloeter** [comment]
You need PHP 5.3+

Some of the features that were used in that version needs PHP 5.3+.
We apologies for any headache this may cause you, but frankly it is better for you to check with your hosting company how can you upgrade the PHP version that you are using, and not only in order to use this plugin. PHP 5.2 should be considered insecure now, and for your own sake you should upgrade.
PHP 5.2 is very old and any support for it from the php developers had ended more then 5 years ago php.net/eol.php.
We know there are peopel how use PHP 5.2 wordpress.org/about/stats and we can’t imagine this people will have no other problems, if they don’t update.
